version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    build: .
    ports: 
      - "4000:4000"
    depends_on:
      - ganache
    
  react:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - dapp

  #   // Package updater: https://updatepackagejson.com/